//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_Selling_Site.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SiteDatabaseEntities : DbContext
    {
        public SiteDatabaseEntities()
            : base("name=SiteDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContactTable> ContactTables { get; set; }
        public virtual DbSet<HiredVehiclesTable> HiredVehiclesTables { get; set; }
        public virtual DbSet<UserTable> UserTables { get; set; }
        public virtual DbSet<VehicleTable> VehicleTables { get; set; }
        public virtual DbSet<VehicleTypeTable> VehicleTypeTables { get; set; }
        public virtual DbSet<Hired_Vehicles_History> Hired_Vehicles_History { get; set; }
    }
}
