//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_Selling_Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hired_Vehicles_History
    {
        public int Id { get; set; }
        public string Hired_By_User { get; set; }
        public string Start_of_Hiring { get; set; }
        public string End_of_Hiring { get; set; }
        public string Image { get; set; }
        public int Daily_Cost { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public int Total_Cost { get; set; }
    }
}
