//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_Selling_Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleTypeTable
    {
        public string VehicleType { get; set; }
    }
}
