//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_Selling_Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleTable
    {
        public string Name { get; set; }
        public string Year { get; set; }
        public int Mileage { get; set; }
        public string Transmission { get; set; }
        public bool Available_for_Hire { get; set; }
        public bool Fixed_for_Hire { get; set; }
        public string Number { get; set; }
        public string Branch { get; set; }
        public string Hiring_Period_Start { get; set; }
        public string Hiring_Period_End { get; set; }
        public string Model { get; set; }
        public string Manufacturer { get; set; }
        public int Daily_Cost { get; set; }
        public int Late_Cost { get; set; }
        public string Image { get; set; }
        public string Vehicle_Type { get; set; }
    }
}
